# Site settings
title: Wasmcov
description: Automated coverage analysis of WASM executables on embedded, blockchain, and other constrained environments.

# Theme settings
theme: jekyll-theme-cayman

# Breadcrumbs
breadcrumbs: true

