[package]
name = "wasmcov"
version = "0.0.1"
edition = "2021"
authors = ["Noah Jelich <n.jelich@hacken.io>"]
description = "A set of helpers for coverage of wasm modules"
license = "MIT"

[lib]
name = "wasmcov"
path = "src/lib.rs"

[dependencies]
uuid = { version = "1.5.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.8.1"

