[package]
name = "wasmcov"
version = "0.0.2"
edition = "2021"
authors = ["Noah Jelich <n.jelich@hacken.io>", "Bartosz Barwikowski <b.barwikowski@hacken.io>"]
description = "A set of helpers for coverage of wasm modules"

license = "Apache-2.0"

readme ="README.md"
documentation = "https://hknio.github.io/wasmcov/"
repository = "https://github.com/hknio/wasmcov"

keywords = ["crypto", "wasm", "blockchain", "testing", "profiling"]
categories = ["development-tools", "embedded", "wasm", "command-line-utilities", "cryptography::cryptocurrencies"]

exclude = [
    "bin/*",
    "docs/*",
]

[lib]
name = "wasmcov"
path = "src/lib.rs"

[dependencies]
uuid = { version = "1.5.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.8.1"

